name: UtilsManager
version: '3.1.1'
main: dev.lars.utilsmanager.UtilsManager
api-version: '1.21.10'
description: A Plugin by Lars for the whole server management
author: LarsEsDoch
website: "https://github.com/LarsEsDoch/UtilsManager"
settings:
  restart-script: start.sh
dependencies:
  server:
    ApiManager:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true


permissions:
  utilsmanager.addcoins:
    default: false
  utilsmanager.backpack:
    default: false
  utilsmanager.backpack.config:
    default: false
  utilsmanager.buy:
    default: false
  utilsmanager.date:
    default: false
  utilsmanager.gift:
    default: false
  utilsmanager.language:
    default: false
  utilsmanager.pay:
    default: false
  utilsmanager.price:
    default: false
  utilsmanager.realtime:
    default: false
  utilsmanager.sell:
    default: false
  utilsmanager.setcoins:
    default: false
  utilsmanager.setspawn:
    default: false
  utilsmanager.shop:
    default: false
  utilsmanager.feature.spawn:
    default: false
  utilsmanager.timer:
    default: false
  utilsmanager.togglebed:
    default: false
  utilsmanager.togglescoreboard:
    default: false
  utilsmanager.wallet:
    default: false
  utilsmanager.rank:
    default: false
  utilsmanager.nick:
    default: false
  utilsmanager.spawnbuild:
    default: false
  utilsmanager.freeze:
    default: false
  utilsmanager.inv:
    default: false
  jes:
    default: false
  utilsmanager.prefix:
    default: false
  utilsmanager.ban:
    default: false
  utilsmanager.home:
    default: false
  utilsmanager.timer.public:
    default: false
  utilsmanager.heal:
    default: false
  utilsmanager.maintenance:
    default: false
  utilsmanager.announce:
    default: false
  utilsmanager.clearchat:
    default: false
  utilsmanager.entity:
    default: false
  utilsmanager.restart:
    default: false
  utilsmanager.search:
    default: false
  utilsmanager.sudo:
    default: false
  utilsmanager.vanish:
    default: false
  utilsmanager.feature.freecam:
    default: false
  utilsmanager.feature.spawn.setspawn: