name: UtilsManager
version: '3.1.1'
main: de.lars.utilsmanager.Main
api-version: '1.21'
description: A Plugin by Lars for the whole server management
author: KompetenzL0s
dependencies:
  server:
    ApiManager:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true


permissions:
  plugin.addcoins:
    default: false
  plugin.backpack:
    default: false
  plugin.backpack.config:
    default: false
  plugin.buy:
    default: false
  plugin.date:
    default: false
  plugin.gift:
    default: false
  plugin.language:
    default: false
  plugin.pay:
    default: false
  plugin.price:
    default: false
  plugin.realtime:
    default: false
  plugin.sell:
    default: false
  plugin.setcoins:
    default: false
  plugin.setspawn:
    default: false
  plugin.shop:
    default: false
  plugin.spawn:
    default: false
  plugin.timer:
    default: false
  plugin.togglebed:
    default: false
  plugin.togglescoreboard:
    default: false
  plugin.wallet:
    default: false
  plugin.rank:
    default: false
  plugin.nick:
    default: false
  plugin.spawnbuild:
    default: false
  plugin.freeze:
    default: false
  plugin.inv:
    default: false
  jes:
    default: false
  plugin.prefix:
    default: false
  plugin.ban:
    default: false
  plugin.home:
    default: false
  ported:
    default: false
  plugin.timer.public:
    default: false
  plugin.heal:
    default: false
  plugin.maintenance:
    default: false
  plugin.announce:
    default: false
  plugin.clearchat:
    default: false
  plugin.entity:
    default: false
  plugin.restart:
    default: false
  plugin.search:
    default: false
  plugin.sudo:
    default: false
  plugin.vanish:
    default: false
  plugin.freecam:
    default: false