name: UtilsManager
version: '3.1.1'
main: de.lars.utilsManager.Main
api-version: '1.21'
description: A Plugin by Lars for the whole server management
author: KompetenzL0s
dependencies:
  server:
    ApiManager:
      load: BEFORE
      required: true
      join-classpath: true


permissions:
  plugin.addcoins:
    default: false
  plugin.backpack:
    default: false
  plugin.backpack.config:
    default: false
  plugin.buy:
    default: false
  plugin.date:
    default: false
  plugin.gift:
    default: false
  plugin.language:
    default: false
  plugin.pay:
    default: false
  plugin.price:
    default: false
  plugin.realtime:
    default: false
  plugin.sell:
    default: false
  plugin.setcoins:
    default: false
  plugin.setspawn:
    default: false
  plugin.shop:
    default: false
  plugin.spawn:
    default: false
  plugin.timer:
    default: false
  plugin.togglebed:
    default: false
  plugin.togglescoreboard:
    default: false
  plugin.wallet:
    default: false
  plugin.rank:
    default: false
  plugin.nick:
    default: false
  plugin.spawnbuild:
    default: false
  plugin.freeze:
    default: false
  plugin.inv:
    default: false
  jes:
    default: false
  plugin.prefix:
    default: false
  plugin.ban:
    default: false
  plugin.home:
    default: false
  ported:
    default: false
  plugin.timer.public:
    default: false
  plugin.heal:
    default: false
  plugin.maintenance:
    default: false
  plugin.announce:
    default: false
  plugin.clearchat:
    default: false
  plugin.entity:
    default: false
  plugin.restart:
    default: false
  plugin.search:
    default: false
  plugin.sudo:
    default: false
  plugin.vanish:
    default: false
  plugin.freecam:
    default: false

commands:
  date:
    description: Zeigt das Datum an

  backpack:
    description: Gibt dir ein Rucksack
    aliases: [ bp ]

  timer:
    aliases: [ t ]
    description: Is halt nen Timer

  spawn:
    description: Teleportiert dich zum Spawn

  setBpSlots:
    description: setzt die Backpack Slots auf gewünschte Menge
    aliases: [ sBp ]

  home:
    description: teleportirt dich zu deiner Base
    aliases: [ h ]

  deletehome:
    description: Löscht ein Home
    aliases: [ dh ]

  sethome:
    description: setzt deine Base
    aliases: [ sh ]

  toggletime:
    description: Wechselt zwischen echter und normaler Zeit
    aliases: [ tt ]

  addcoins:
    description: Fügt dir Coins hinzu
    aliases: [ ac ]

  pay:
    description: Überweist anderen Geld
    aliases: [ p ]

  wallet:
    description: Zeigt wie viel du oder jemand anders auf dem Konto hat
    aliases: [ w ]

  setcoins:
    description: Setzte den Kontostand eines bestimmten Spieler auf ein bestimmten Wert
    aliases: [ sc ]

  buy:
    description: Lässt dich etwas mit deinen Coins kaufen
    aliases: [ b ]

  sell:
    description: Lässt dich verschiedene Items verkaufen
    aliases: [ s ]

  language:
    description: Ändert die Sprache
    aliases: [ l ]

  gifts:
    description: Gibt dir dein Startguthaben

  togglebed:
    description: Läst dich nicht mehr am Spawn spawnen
    aliases: [ tb ]

  shop:
    description: öffnet den Shop

  prices:
    description: sagt dir die Preise de shopsw

  setrank:
    description: verwalltet ränge

  togglescoreboard:
    description: Wechselt zwischen Scoreboard und keinem

  rankshop:
    description: Du kannst Ränge kaufen

  nick:
    description: Du kannst du nicken
    aliases: [ n ]

  freezee:
    description: Du kannst jemanden frezzen

  br:
    description: ----

  invsee:
    description: Läst dich das Inventar von jemanden öffnen

  prefix:
    description: Ändert dein Prefix

  ban:
    description: Bannt jemanden

  unban:
    description: entbannt jemanden

  status:
    description: ändert dein status

  performance:
    description: zeigt die performance des servers

  report:
    description: zeigt jemanden an

  court:
    description: court befehle

  chunk:
    description: Chunk befehle
    aliases: [ ch ]

  heal:
    description: HEilt jemanden

  feed:
    description: Füttert jemanden

  claimgift:
    description: läst dich ein Geschenk anfordern

  entity:
    description: lässt dich entitys zu spawnen

  clearchat:
    description: lässt dich den chat clearen

  test1:
    description: asdjhkibs

  search:
    description: Sucht alle Spieler auf dem Server

  freecam:
    description: Spectator

  freecamleave:
    description: Leave Spectator

  serverrestart:
    description: Restarts the Server after a period of time

  sudo:
    description: Let you perform a command from another player

  timeout:
    description: Timeouts a player

  vanish:
    description: Makes you invisible
    aliases: [ v ]

  announce:
    description: Announces a Message

  maintenancetest:
    description: Control the maintenance
